// Lightweight course summary data for listing pages (Home, Courses).
// Does NOT include curriculum, projects, faqs, reviews, mentors, outcomes
// to keep the critical bundle small. Full data is in mockDb.js for CourseDetails.

export const COURSES_SUMMARY = [
  {
    id: 'artificial-intelligence',
    techStack: ['Python', 'Neural Networks', 'NLP', 'Generative AI', 'TensorFlow', 'Hugging Face'],
    title: 'Artificial Intelligence',
    category: 'AI/ML/DS/DA',
    level: 'Basic to Intermediate',
    duration: '3 Months',
    fee: 14000,
    originalFee: 16000,
    selfPacedFee: 8000,
    selfPacedOriginalFee: 14000,
    rating: 4.8,
    enrollments: '1,250+',
    overview: 'Understand neural networks, natural language processing (NLP), computer vision, and generative AI frameworks using Python and modern library architectures.',
  },
  {
    id: 'machine-learning',
    techStack: ['Python', 'NumPy', 'Pandas', 'Matplotlib', 'Seaborn', 'Scikit-Learn'],
    title: 'Machine Learning',
    category: 'AI/ML/DS/DA',
    level: 'Basic to Intermediate',
    duration: '3 Months',
    fee: 14000,
    originalFee: 16000,
    selfPacedFee: 8000,
    selfPacedOriginalFee: 14000,
    rating: 4.8,
    enrollments: '1,450+',
    overview: 'Master supervised and unsupervised machine learning algorithms, model evaluation metrics, and feature engineering techniques using Python and Scikit-Learn.',
  },
  {
    id: 'full-stack-web',
    techStack: ['HTML5', 'CSS3', 'JavaScript', 'React', 'Node.js', 'Express', 'MongoDB'],
    title: 'Full Stack Web Development (MERN)',
    category: 'Full Stack Development',
    level: 'Basic to Intermediate',
    duration: '4 Months',
    fee: 15000,
    originalFee: 18000,
    selfPacedFee: 6000,
    selfPacedOriginalFee: 8000,
    rating: 4.7,
    enrollments: '4,500+',
    overview: 'Learn modern web development using HTML5, CSS3, JavaScript, React, Node.js, Express, and MongoDB. Build real-world web applications and deploy them to the cloud.',
  },
  {
    id: 'digital-marketing-cert',
    techStack: ['Google Ads', 'Meta Ads', 'Google Analytics', 'SEO', 'Email Marketing'],
    title: 'Digital Marketing',
    category: 'Digital Marketing',
    level: 'Basic to Intermediate',
    duration: '3 Months',
    fee: 12000,
    originalFee: 15000,
    selfPacedFee: 5000,
    selfPacedOriginalFee: 7000,
    rating: 4.6,
    enrollments: '1,800+',
    overview: 'Master SEO, Content Marketing, Google Ads, Meta Ads (Facebook & Instagram), Email Marketing, and Analytics (GA4) to drive high ROI lead-generation.',
  },
  {
    id: 'data-science',
    techStack: ['Python', 'SQL', 'Pandas', 'NumPy', 'Statistics'],
    title: 'Data Science',
    category: 'AI/ML/DS/DA',
    level: 'Basic to Intermediate',
    duration: '3 Months',
    fee: 14000,
    originalFee: 16000,
    selfPacedFee: 6000,
    selfPacedOriginalFee: 8000,
    rating: 4.7,
    enrollments: '1,100+',
    overview: 'Learn statistics, data preprocessing, SQL database querying, exploratory analysis in Pandas, and predictive models in Python.',
  },
  {
    id: 'data-analytics',
    techStack: ['Excel', 'SQL', 'PowerBI', 'Tableau', 'Dashboard Design'],
    title: 'Data Analytics',
    category: 'AI/ML/DS/DA',
    level: 'Basic to Intermediate',
    duration: '3 Months',
    fee: 14000,
    originalFee: 16000,
    selfPacedFee: 6000,
    selfPacedOriginalFee: 8000,
    rating: 4.7,
    enrollments: '1,200+',
    overview: 'Master data visualization and business intelligence by querying databases with SQL, organizing data in Excel, and building interactive dashboards in PowerBI and Tableau.',
  },
  {
    id: 'hr-mgmt',
    techStack: ['ATS Systems', 'Payroll Tools', 'HR Analytics', 'Excel'],
    title: 'Human Resource Management & Operations',
    category: 'HR',
    level: 'Basic to Intermediate',
    duration: '2 Months',
    fee: 9000,
    originalFee: 12000,
    selfPacedFee: 5000,
    selfPacedOriginalFee: 7000,
    rating: 4.5,
    enrollments: '800+',
    overview: 'Learn modern HR practices, recruitment strategies, onboarding, HR analytics, payroll administration, and employee relations.',
  },
  {
    id: 'stock-market',
    techStack: ['Technical Analysis', 'Fundamental Analysis', 'Trading Sheets', 'Risk Management'],
    title: 'Stock Market & Financial Analysis',
    category: 'Stock Market',
    level: 'Basic to Intermediate',
    duration: '2 Months',
    fee: 9000,
    originalFee: 12000,
    selfPacedFee: 5000,
    selfPacedOriginalFee: 7000,
    rating: 4.6,
    enrollments: '1,200+',
    overview: 'Understand financial markets, technical analysis, fundamental analysis, risk management, and trading strategies.',
  },
  {
    id: 'cyber-security',
    techStack: ['Kali Linux', 'Wireshark', 'Metasploit', 'Nmap', 'OWASP Top 10'],
    title: 'Cyber Security',
    category: 'Cyber Security',
    level: 'Basic to Intermediate',
    duration: '3 Months',
    fee: 12000,
    originalFee: 15000,
    selfPacedFee: 6000,
    selfPacedOriginalFee: 8000,
    rating: 4.7,
    enrollments: '950+',
    overview: 'Understand network security, cryptography, vulnerability assessment, web application security, and ethical hacking concepts.',
  },
  {
    id: 'cloud-computing',
    techStack: ['AWS', 'AWS EC2', 'AWS S3', 'VPC Routing', 'Auto Scaling'],
    title: 'Cloud Computing',
    category: 'Cloud Computing',
    level: 'Basic to Intermediate',
    duration: '2 Months',
    fee: 10000,
    originalFee: 12000,
    selfPacedFee: 5000,
    selfPacedOriginalFee: 7000,
    rating: 4.8,
    enrollments: '1,400+',
    overview: 'Get introduced to cloud infrastructure. Learn about computing, storage, networking, database services, and deployment models on AWS.',
  },
];

// Helper to find a course summary by id (for listing pages)
export const findCourseSummary = (id) => COURSES_SUMMARY.find(c => c.id === id) || null;
